import json

from app.main import create_app


def test_openapi_is_a_consumer_integration_reference(test_settings) -> None:
    schema = create_app(test_settings).openapi()

    assert schema["info"]["title"] == "Test Messaging Platform"
    assert schema["info"]["version"] == "0.1.0"
    assert {tag["name"] for tag in schema["tags"]} == {
        "System",
        "Messages",
        "Templates",
        "Billing",
        "Webhooks",
    }
    assert schema["components"]["securitySchemes"]["ApplicationApiKey"] == {
        "type": "http",
        "description": (
            "Application API key generated by Fazilabs Messaging. Send it as "
            "`Authorization: Bearer <application-api-key>`."
        ),
        "scheme": "bearer",
    }


def test_openapi_marks_consumer_auth_and_provider_webhooks(test_settings) -> None:
    schema = create_app(test_settings).openapi()
    protected_operations = (
        ("/api/v1/messages/text", "post"),
        ("/api/v1/messages/template", "post"),
        ("/api/v1/messages/{message_id}", "get"),
        ("/api/v1/messages", "get"),
        ("/api/v1/templates", "get"),
        ("/api/v1/billing-accounts/{external_id}/balance", "get"),
        ("/api/v1/billing-accounts/{external_id}/usage", "get"),
    )
    for path, method in protected_operations:
        assert schema["paths"][path][method]["security"] == [{"ApplicationApiKey": []}]

    assert "security" not in schema["paths"]["/health"]["get"]
    assert "security" not in schema["paths"]["/ready"]["get"]
    assert "security" not in schema["paths"]["/webhooks/whatsapp"]["post"]
    assert "security" not in schema["paths"]["/webhooks/advanta"]["post"]


def test_openapi_documents_idempotency_and_template_examples(test_settings) -> None:
    schema = create_app(test_settings).openapi()
    for path in ("/api/v1/messages/text", "/api/v1/messages/template"):
        parameters = schema["paths"][path]["post"]["parameters"]
        header = next(item for item in parameters if item["name"] == "Idempotency-Key")
        assert header["in"] == "header"
        assert "caller-generated" in header["description"]
        assert "HTTP 409" in header["description"]

    media_type = schema["paths"]["/api/v1/messages/template"]["post"]["requestBody"]["content"][
        "application/json"
    ]
    examples = media_type["examples"]
    assert examples["whatsapp"]["value"]["parameters"]["results_path"] == ("example-access-token")
    assert examples["sms"]["value"]["parameters"]["results_url"] == (
        "https://example.com/results/example-access-token"
    )
    assert examples["whatsapp"]["value"]["to"] == "254700000000"
    assert examples["sms"]["value"]["to"] == "254700000000"


def test_openapi_contains_no_secret_values(test_settings) -> None:
    serialized = json.dumps(create_app(test_settings).openapi()).lower()
    assert "test-access-token" not in serialized
    assert "test-app-secret" not in serialized
    assert "fzmsg_" not in serialized


def test_openapi_documents_database_readiness(test_settings) -> None:
    operation = create_app(test_settings).openapi()["paths"]["/ready"]["get"]

    assert operation["tags"] == ["System"]
    assert operation["summary"] == "Check application readiness"
    assert "PostgreSQL" in operation["description"]
    assert "503" in operation["responses"]
